### ISSUE TITLE
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be indexed. Have you modified the index?'

### ISSUE THREAD

**Issue by dazzag24** [tantivy-search/tantivy-cli#17]
Following instructions for tantivy-cli and encountered the following message:

100000 Docs
126767571 docs / hour
200000 Docs
61979511 docs / hour
300000 Docs
45240748 docs / hour
400000 Docs
80860935 docs / hour
500000 Docs
37683017 docs / hour
600000 Docs
43229461 docs / hour
700000 Docs
40245879 docs / hour
800000 Docs
53577161 docs / hour
900000 Docs
63745697 docs / hour
1000000 Docs
29509239 docs / hour
1100000 Docs
38593585 docs / hour
1200000 Docs
29582937 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
1300000 Docs
37100076 docs / hour
1400000 Docs
34933046 docs / hour
1500000 Docs
50002639 docs / hour
1600000 Docs
36648185 docs / hour
1700000 Docs
43451182 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
1800000 Docs
36208233 docs / hour
1900000 Docs
36207170 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
2000000 Docs
34476517 docs / hour
2100000 Docs
37284904 docs / hour
2200000 Docs
34497714 docs / hour
2300000 Docs
51197990 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
2400000 Docs
35314496 docs / hour
2500000 Docs
35938516 docs / hour
2600000 Docs
35805693 docs / hour
2700000 Docs
45073260 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
2800000 Docs
40951638 docs / hour
2900000 Docs
32014644 docs / hour
3000000 Docs
53152959 docs / hour
3100000 Docs
41247139 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
3200000 Docs
48792619 docs / hour
3300000 Docs
44430117 docs / hour
3400000 Docs
23955508 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
3500000 Docs
35455778 docs / hour
3600000 Docs
42539936 docs / hour
3700000 Docs
39232883 docs / hour
3800000 Docs
36802974 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
3900000 Docs
32920675 docs / hour
4000000 Docs
35512050 docs / hour
4100000 Docs
42407731 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
4200000 Docs
59604287 docs / hour
4300000 Docs
42813997 docs / hour
4400000 Docs
40106933 docs / hour
4500000 Docs
48629958 docs / hour
4600000 Docs
41602207 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
4700000 Docs
43152739 docs / hour
4800000 Docs
39880076 docs / hour
4900000 Docs
33744674 docs / hour
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
5000000 Docs
40354826 docs / hour
Commit succeed, docstamp at 5032119
Waiting for merging threads
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
thread '<unnamed>' panicked at 'Encounterred a field that is not supposed to be
                         indexed. Have you modified the index?', /checkout/src/libcore/option.rs:823:4
ERROR:tantivy::indexer::index_writer: Some merging thread failed Error(ErrorInThread("Failed to join merging thread."), State { next_error: Some(Error(ErrorInThread("Merging thread failed."), State { next_error: None, backtrace: None })), backtrace: None })
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Indexing failed : Error(ErrorInThread(\"Failed to join merging thread.\"), State { next_error: Some(Error(ErrorInThread(\"Merging thread failed.\"), State { next_error: None, backtrace: None })), backtrace: None })"', /checkout/src/libcore/result.rs:860:4

real	7m54.105s
user	22m39.868s
sys	3m58.152s

Steps to reproduce:

mkdir wikipedia-index
tantivy new -i wikipedia-index
See meta file here: [meta.json.txt](https://github.com/tantivy-search/tantivy-cli/files/1156389/meta.json.txt)
time cat wiki-articles.json | tantivy index -i ./wikipedia-index

Do you need any further info?

**Comment by fulmicoton** [comment]
Thanks for the bug report. It is perfect.

So the error message is complaining that you had a 

- directory with an empty index
- indexed some documents
- changed the schema
- added some more document

is that correct?

A change of schema is not supported by tantivy.

**Comment by dazzag24** [comment]
When I first saw this message I had added the small dataset (http://fulmicoton.com/tantivy-files/wiki-articles-1000.json) and then later added the full 5m wiki-articles.json.    I suspected that this could have been an unsupported operation, so I deleted the wikipedia-index directory and then started from scratch following exactly the instructions in the tantivy-cli README.md.   I then saw the same errors as detailed above.   So in summary I have not changed the schema.

Please advise on how I can help track down the root cause.

Thanks

**Comment by fulmicoton** [comment]
It supposedly should work just fine as long as you didn't change the schema... So this could be a bug. Let me try to reproduce.

**Comment by dazzag24** [comment]
Thanks.  Let me know if you need any more details from my system or want me to run any tests.

As a very minor issue, I notice that "encountered" is spelt with an extra 'r' in multiple places in the codebase:
https://github.com/tantivy-search/tantivy/search?utf8=%E2%9C%93&q=Encounterred&type=

**Comment by fulmicoton** [comment]
I have been able to reproduce thanks.

**Comment by fulmicoton** [comment]
The fix is on the way... I moved the issue to tantivy (as opposed to tantivy-cli).
Thanks for reporting it is a pretty shameful bug.

**Comment by fulmicoton** [comment]
@dazzag24 Just published the fix in 0.4.2.

The binaries are on the way.

**Comment by dazzag24** [comment]
Hi,

I had built tantivy from source yesterday, but had installed tantiy-cli using "cargo install tantivy-cli".   Was tantivy-cli using the tantivy lib that I built or did it pull down it's own copy?

I have already done a "git pull" and a rebuild of tantivy since you submitted the fix earlier.  

Thanks

**Comment by fulmicoton** [comment]
I think it pulled its own copy.

**Comment by dazzag24** [comment]
OK. Thanks.

How do I pull the updated version in that case.

Thanks

Darren

**Comment by fulmicoton** [comment]
I republished tantivy-cli too. So cargo install tantivy-cli should work fine now.

Alternatively I republished binaries for Mac OS and Linux. (The Linux one does not include any AVX2 instructions anymore.)

**Comment by dazzag24** [comment]
cargo install tantivy-cli
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading tantivy-cli v0.4.2
  Installing tantivy-cli v0.4.2
error: binary `tantivy` already exists in destination as part of
`tantivy-cli v0.4.0`
Add --force to overwrite

So I had to use --force, but the indexing now seems to be working without
error.

Thanks
