### ISSUE TITLE
timing in tutorial is outdated

### ISSUE THREAD

**Issue by vandenoever** [tantivy-search/tantivy-cli#19]
The tutorial tantivy-cli/README.md was written for Tantivy 0.2. It states "On my computer (8 core Xeon(R) CPU X3450 @ 2.67GHz), on 8 threads, indexing wikipedia takes around 9 minutes."

https://fulmicoton.com/posts/behold-tantivy-part2/ states "4 threads, 8 gigabytes, 94s".

**Comment by fulmicoton** [comment]
Yes, it certainly does not take 9minutes anymore. Just to be clear though the timing in my blog post is without any stored fields... Only the inverted index.

In the tutorial we do have stored fields so it might take a little bit longer. I need to time it again.
