### ISSUE TITLE
Incorrect meta.json format

### ISSUE THREAD

**Issue by nicot** [tantivy-search/tantivy-cli#20]
I think the JSON format is not quite right in this version of tantivy-cli. I can't get searching to work with the code as-is. There might be some issues with the version of tantivy that it depends on (0.4.3). Since 0.4.3, there have been some changes to the way tantivy serializes the Schema.

Steps to reproduce:

```
cargo install tantivy-cli
mkdir index
tantivy new -i index
Creating new index 
Let's define it's schema! 



New field name  ? text
Text or unsigned 32-bit integer (T/I) ? T
Should the field be stored (Y/N) ? Y
Should the field be indexed (Y/N) ? Y
Should the field be tokenized (Y/N) ? Y
Should the term frequencies (per doc) be in the index (Y/N) ? Y
Should the term positions (per doc) be in the index (Y/N) ? Y
Add another field (Y/N) ? N

[
  {
    "name": "text",
    "type": "text",
    "options": {
      "indexing": "position",
      "stored": true
    }
  }
]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Error(CorruptedFile(\"meta.json\"), State { next_error: Some(ErrorImpl { code: Message(\"invalid type: sequence, expected struct Schema\"), line: 3, column: 12 }), backtrace: None })"', src/libcore/result.rs:916:4
note: Run with `RUST_BACKTRACE=1` for a backtrace
```

I can also reproduce this issue manually creating the meta.json file and running tantivy search.

Here's the JSON that is created with tantivy new:
```
{
  "segments": [],
  "schema": [
    {
      "name": "text",
      "type": "text",
      "options": {
        "indexing": "position",
        "stored": true
      }
    }
  ],
  "opstamp": 0
}
```

I was able to get it working here: https://github.com/nicot/tantivy-cli/commit/99fe211ce22885bcd91e374b61849c3890183c04.

**Comment by fulmicoton** [comment]
I still need more information. Your problem is that you want a version of `tantivy-cli` to create index that are usable for `tantivy 0.5` ?

tantivy 0.5 is not published yet. I will update tantivy-cli to work with tantivy 0.5 before it gets published. That should happen next week.

Let me know if I misunderstood.

**Comment by nicot** [comment]
No, I just want to run `tantivy-cli`. Any version is fine with me. The steps in the README do not work (or I'm doing them wrong).

**Comment by fulmicoton** [comment]
I think I was able to reproduce with `cargo install tantivy-cli`.
The master branch seems ok, let me try and publish `tantivy-cli` hopefully this should solve your problem.

**Comment by fulmicoton** [comment]
I think it should be fixed in `tantivy-cli 0.4.5`. You might new to run `cargo install tantivy-cli --force` to update the version.

**Comment by nicot** [comment]
It works now, thanks!

**Comment by fulmicoton** [comment]
@nicot thanks for the report !
