### ISSUE TITLE
How to delete a document?

### ISSUE THREAD

**Issue by zjgreen** [tantivy-search/tantivy-cli#30]
Is there a way using the CLI to delete a document, or to have some way to replace a duplicate document given a certain field name?

**Comment by fulmicoton** [comment]
The functionality exists in `tantivy`, as it cannot be done with `tantivy-cli` at the moment. 

[`Toshi`](https://github.com/hntd187/Toshi) is likely to become a cleaner / more complete project than `tantivy-cli`.

**Comment by fulmicoton** [comment]
@zjgreen  I opened https://github.com/hntd187/Toshi/issues/2
