### ISSUE TITLE
Merge failed with "out of bounds" error

### ISSUE THREAD

**Issue by zjgreen** [tantivy-search/tantivy-cli#32]
Hi, I've been indexing documents (`./tantivy index -i index --nomerge`) and then merging every 5000 documents with `./tantivy merge -i index`.

It's been working, but now I am unable to merge successfully and receive the error below.

Does anyone have suggestions on how to remedy this, or what other information I can provide to help debug this?

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 196916 but the index is 201379', /checkout/src/libcore/slice/mod.rs:2051:10
stack backtrace:
   0:     0x55b065363292 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h0c827793368fbc95
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55b06535610b - std::panicking::default_hook::{{closure}}::h78ff2c77689d1451
                               at libstd/sys_common/backtrace.rs:71
   2:     0x55b065355217 - std::panicking::rust_panic_with_hook::hcd548010674c2347
                               at libstd/panicking.rs:227
                               at libstd/panicking.rs:463
   3:     0x55b0653582fc - std::panicking::begin_panic_fmt::hb088e4aa19a35612
                               at libstd/panicking.rs:350
   4:     0x55b06536718a - core::panicking::panic_fmt::hed27deb097b8209d
                               at libstd/panicking.rs:328
   5:     0x55b06536713f - core::panicking::panic_bounds_check::h7b819858526f3dc9
                               at libcore/panicking.rs:58
   6:     0x55b0651af65d - <tantivy::indexer::merger::IndexMerger as tantivy::core::segment::SerializableSegment>::write::hcfbc180f0ad9e058
   7:     0x55b0651865e0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9497c20b2a3a7790
   8:     0x55b065193002 - <F as alloc::boxed::FnBox<A>>::call_box::h3b1fe427063780b8
   9:     0x55b0653509e3 - std::sys::unix::thread::Thread::new::thread_start::haaed00ecdbc477ec
                               at /checkout/src/liballoc/boxed.rs:648
  10:     0x7f07c48dc063 - start_thread
  11:     0x7f07c43fb62c - clone
  12:                0x0 - <unknown>
thread 'main' panicked at 'Merge failed: Canceled', libcore/result.rs:945:5
stack backtrace:
   0:     0x55b065363292 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h0c827793368fbc95
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55b06535610b - std::panicking::default_hook::{{closure}}::h78ff2c77689d1451
                               at libstd/sys_common/backtrace.rs:71
   2:     0x55b065355217 - std::panicking::rust_panic_with_hook::hcd548010674c2347
                               at libstd/panicking.rs:227
                               at libstd/panicking.rs:463
   3:     0x55b0653582fc - std::panicking::begin_panic_fmt::hb088e4aa19a35612
                               at libstd/panicking.rs:350
   4:     0x55b06536718a - core::panicking::panic_fmt::hed27deb097b8209d
                               at libstd/panicking.rs:328
   5:     0x55b06537c380 - core::result::unwrap_failed::hb79615b688308113
   6:     0x55b06537bfb1 - tantivy::commands::merge::run_merge_cli::h3a81bcfc9e57e723
   7:     0x55b0653aa2f3 - tantivy::main::hc657201e713a0921
   8:     0x55b0650f0152 - std::rt::lang_start::{{closure}}::h10ca1e4558686e03
   9:     0x55b0653a3d58 - main
  10:     0x7f07c4334b44 - __libc_start_main
  11:     0x55b0650eff01 - <unknown>
  12:                0x0 - <unknown>
```

**Comment by zjgreen** [comment]
```
node@9645f801503a:/tantivy$ ./src/tantivy --version
Tantivy 0.5.0
```

**Comment by fulmicoton** [comment]
A shameful series of bugs have been discovered for tantivy 0.5.0, and 0.5.1 this version and have been fixed since tantivy 0.5.2. I am not sure which one of them is hitting you, but one of them is most likely the cause for your error. It seems like I never published `tantivy-cli` for 0.5.2.

Is updating to 0.6.1 possible for you? 
The index format has changed which means this is only possible if reindexing your data is feasible for you (there is no converter yet).

If you are stuck, I can publish a tantivy-cli 0.5.2 depending on version tantivy 0.5.2.

**Comment by zjgreen** [comment]
Thanks for your help with this - much appreciated!

Our index is still searchable, so I suppose if future versions of Tantivy's schemas aren't backward compatible, we might as well upgrade sooner rather than later. 

Do you have any theories of what could cause this so we can avoid in the future? We're doing lots of inserts with large documents, and frequent deletes + merging.

**Comment by fulmicoton** [comment]
There is nothing wrong with your usage. This was an actual bug in tantivy.

As for the detail of the possible culprits :
- https://github.com/tantivy-search/tantivy/issues/274
- https://github.com/tantivy-search/tantivy/issues/280
- https://github.com/tantivy-search/tantivy/issues/254

#254 is the most likely culprit in your case I would say

**Comment by fulmicoton** [comment]
Also, every minor version may break the index format until I release `1.0`.
Make sure you keep a way to reindex your entire index when you want to upgrade tantivy's version.

If your use case requires a huge amount of data (terabytes of logs) for instance, you can write a program to deserialize your previous index format and reserialize it into the new index format. A user already uses that method to very rapidly convert large Lucene indices.
