### ISSUE TITLE
Match Some Features from Whoosh

### ISSUE THREAD

**Issue by logannc** [tantivy-search/tantivy-cli#33]
I'm not sure how to split this up and I don't want to spam with issues.

[Whoosh](https://whoosh.readthedocs.io/en/latest/intro.html) is a great, pure python search engine/tool that accomplishes most of the goals of this project (sans Rust-level performance). Matching some of their features would make tantivy something useful for a production application.

A couple of features that tantivy could use that would make it more useful/production ready:

- [ ] More Schema types: KEYWORD, ID, STORED, DATETIME, BOOLEAN, etc. 
- [ ] Analyzers in general - I don't think I saw them when looking at the docs. This can be useful for creating comma separated field for the schema or something (though in rust maybe that would be more strongly typed - and I'm not sure why we're using this instead of the `KEYWORD` type in our application - presumably there is *some* difference).
- [ ] general NLP tools like from https://whoosh.readthedocs.io/en/latest/stemming.html

**Comment by logannc** [comment]
I now realize that this is the `tantivy-cli` repo, not the `tantivy` repo. That explains a lot...

**Comment by fulmicoton** [comment]
Closing.
