### ISSUE TITLE
Is there a way to output text-query similarity score in the search results?

### ISSUE THREAD

**Issue by francoguilherme** [tantivy-search/tantivy-cli#40]

**Comment by fulmicoton** [comment]
Right now no. But that would be simple to add that.

**Comment by francoguilherme** [comment]
Can you help me with that? I'm not familiar with RUST but I really want to use Tantivy.

**Comment by fulmicoton** [comment]
Added scores in the serve command payload  in master, will publish a new version of tantivy-cli that includes scores.

You might want to have a look at toshi too if you want to use tantivy without writing any rust.
