### ISSUE TITLE
Remove Cargo.lock from repository

### ISSUE THREAD

**Issue by klangner** [tantivy-search/tantivy-cli#41]
I think `Cargo.lock` should be added to .gitignore. Now after each compilation on different machine it changes.
Also while changing .gitignore, can we also add the following 2 lines to it:
```
.idea/
*.iml
```
To ignore IDEA IDE files?

**Comment by fulmicoton** [comment]
I think this is the right practise for crates producing a binary.

The cargo.lock is not supposed to be updated if the versions in it are compatible with the cargo.toml.

**Comment by klangner** [comment]
I think this would be ok if we have exact version number for each component. Not something like:
clap = "2"

Since now when I clone this repo and run `cargo build` on it Cargo.lock will be modified. It doesn't force exact versions numbers on my side.
It means that if I will create PR it will always contain modified 'Cargo.lock` in it.

**Comment by fulmicoton** [comment]
I misunderstand your ticket. (the title is quite misleading)

You just want to add it to .gitignore is this correct?
I'd like to keep it as is to ensure I don't forget updating it on releases.

I'm ok with adding 
```
.idea/
*.iml
```
to .gitignore.

**Comment by klangner** [comment]
My main point was about adding Cargo.lock to .gitignore and remove it from the git repo.

But after reading rust documentation it looks that they recommend for binaries adding Cargo.lock to the repo.
The problem here is then that `cargo build` shouldn't update cargo.lock on my computer. It should instead pick the right versions from this file.
Not sure why this happened.

**Comment by fulmicoton** [comment]
I think the meta reason is that I updated master and not develop. You might want to retry. Closing. Please send a PR if you want to put your editor files in the .gitignore file. I'm ok with that.
