### ISSUE TITLE
[feature req] allow real json in indexing

### ISSUE THREAD

**Issue by azah** [tantivy-search/tantivy-cli#43]
The example in the demo is not real json. Serializers like serde will serialize in the format of:

```json
[
  {object1},
  {object2}
]
```
for a `Vec<MyStruct>`.

**Comment by fulmicoton** [comment]
The current format is called [LDJSON](https://en.wikipedia.org/wiki/JSON_streaming).

I want to keep `tantivy-cli` as small as possible and this feature request does not make it possible to do something that was not possible before.

Also JSON for a stream of document has a lot of issue. For instance, on a CPU with many cores it is possible that tantivy's indexing outpaces json parsing. In that case, we want to parse json on more than one thread.
Splitting the payload into documents with this format is very complicated. Without scan, it is actually impossible. (granted we do scan today).
