### ISSUE TITLE
Panic at "tantivy new"

### ISSUE THREAD

**Issue by DiSToAGe** [tantivy-search/tantivy-cli#44]
Creating a new index, immediately give panic after question (with our without existing directory)

Tantivy display :

Creating new index 
Let's define it's schema! 

New field name  ? thread 'main' panicked at 'Failed to read line', src/libcore/option.rs:1034:5

I'm using tanticy-clin 0.10.0

**Comment by DiSToAGe** [comment]
error on my station not a bug

**Comment by fulmicoton** [comment]
@DiSToAGe  Thanks for the update!
