### ISSUE TITLE
Successfully build on target "aarch64-unknown-linux-musl" but got "Illegal instruction (core dumped)" error when run

### ISSUE THREAD

**Issue by greentornado** [tantivy-search/tantivy-cli#63]
Please help me.
The machine uname is
`Linux 4.4.59+ #23824 SMP Fri Sep 7 12:53:01 CST 2018 aarch64 GNU/Linux synology_rtd1296_ds418`

**Comment by fulmicoton** [comment]
You need to find the right target / right compilation flags for your platform. This is not related to tantivy so I will close this ticket.
The rust user forum is probably a better bet.

As a pointer, I suspect that your problem is that you need to switch to soft floats.
