### ISSUE TITLE
Not compiled

### ISSUE THREAD

**Issue by vchugreev** [tantivy-search/tantivy-cli#9]
D:\Projects>cargo install tantivy-cli
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling httparse v1.2.1
   Compiling libc v0.2.19
   Compiling ansi_term v0.9.0
   Compiling unicode-normalization v0.1.3
   Compiling modifier v0.1.0
   Compiling memchr v0.1.11
   Compiling traitobject v0.0.1
   Compiling num_cpus v1.2.1
   Compiling ansi_term v0.8.0
   Compiling aho-corasick v0.5.3
   Compiling strsim v0.5.2
   Compiling utf8-ranges v0.1.3
   Compiling itoa v0.1.1
   Compiling typeable v0.1.2
   Compiling dtoa v0.2.2
   Compiling byteorder v0.4.2
   Compiling traitobject v0.0.3
   Compiling unsafe-any v0.4.1
   Compiling error v0.1.9
   Compiling rand v0.3.15
   Compiling unicode-width v0.1.4
   Compiling itertools v0.4.19
   Compiling matches v0.1.4
   Compiling regex-syntax v0.3.9
   Compiling unicode-bidi v0.2.4
   Compiling sequence_trie v0.0.13
   Compiling bitflags v0.7.0
   Compiling lazy_static v0.1.16
   Compiling log v0.3.6
   Compiling tempdir v0.3.5
   Compiling rustc-serialize v0.3.22
   Compiling mime v0.2.2
   Compiling hpack v0.2.0
   Compiling vec_map v0.6.0
   Compiling serde v0.8.21
   Compiling crossbeam v0.2.10
   Compiling chan v0.1.18
   Compiling byteorder v0.5.3
   Compiling typemap v0.3.3
   Compiling plugin v0.2.6
   Compiling winapi-build v0.1.1
   Compiling getopts v0.2.14
   Compiling semver v0.1.20
   Compiling solicit v0.4.4
   Compiling conduit-mime-types v0.7.3
   Compiling rustc_version v0.1.7
   Compiling pulldown-cmark v0.0.3
   Compiling unicase v1.4.0
   Compiling tempfile v2.1.4
   Compiling num-traits v0.1.36
   Compiling winapi v0.2.8
   Compiling serde_json v0.8.4
   Compiling skeptic v0.6.1
   Compiling num-integer v0.1.32
   Compiling num-complex v0.1.35
   Compiling num-iter v0.1.32
   Compiling num-bigint v0.1.35
   Compiling idna v0.1.0
   Compiling kernel32-sys v0.2.2
   Compiling ascii v0.7.1
   Compiling combine v2.0.0
   Compiling num-rational v0.1.35
   Compiling url v1.2.4
   Compiling num v0.1.36
   Compiling serde v0.6.15
   Compiling uuid v0.1.18
   Compiling num_cpus v0.2.13
   Compiling unicode-segmentation v0.1.3
   Compiling gcc v0.3.41
   Compiling bincode v0.4.1
   Compiling language-tags v0.2.2
   Compiling lz4 v1.20.0
   Compiling lz4-sys v1.0.1+1.7.3
   Compiling tantivy v0.2.0
Build failed, waiting for other jobs to finish...
error: failed to compile `tantivy-cli v0.2.0`, intermediate artifacts can be found at `C:\Users\chvl\AppData\Local\Temp\cargo-install.x08urL3FwU1p`

Caused by:
  failed to run custom build command for `tantivy v0.2.0`
process didn't exit successfully: `C:\Users\chvl\AppData\Local\Temp\cargo-install.x08urL3FwU1p\release\build\tantivy-55cf4812ba42e161\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to make simdcomp: Не удается найти указанный файл. (os error 2)', C:\Users\chvl\.cargo\registry\src\github.com-1ecc6299db9ec823\tantivy-0.2.0\build.rs:11
note: Run with `RUST_BACKTRACE=1` for a backtrace.

***

D:\Projects>cargo -V
cargo 0.15.0-nightly (298a012 2016-12-20)

D:\Projects>rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)

Help me please

**Comment by vchugreev** [comment]
Ok. I switched on nightly, but the problem with the compilation tantivy-cli on Windows preserved:

D:\Projects>cargo install tantivy-cli
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading tantivy-cli v0.2.0
 Downloading tantivy v0.2.0
 Downloading urlencoded v0.4.1
 Downloading staticfile v0.3.1
 Downloading persistent v0.2.1
 Downloading mount v0.2.1
 Downloading iron v0.4.0
 Downloading ansi_term v0.8.0
 Downloading env_logger v0.3.5
 Downloading clap v2.19.3
 Downloading bodyparser v0.4.1
 Downloading url v1.2.4
 Downloading plugin v0.2.6
 Downloading serde_json v0.8.4
 Downloading serde v0.8.22
 Downloading dtoa v0.2.2
 Downloading itoa v0.1.1
 Downloading error v0.1.9
 Downloading typemap v0.3.3
 Downloading conduit-mime-types v0.7.3
 Downloading modifier v0.1.0
 Downloading hyper v0.9.14
 Downloading matches v0.1.4
 Downloading idna v0.1.0
 Downloading unicode-normalization v0.1.3
 Downloading unicode-bidi v0.2.4
 Downloading traitobject v0.0.3
 Downloading typeable v0.1.2
 Downloading unsafe-any v0.4.1
 Downloading solicit v0.4.4
 Downloading cookie v0.2.5
 Downloading unicase v1.4.0
 Downloading httparse v1.2.1
 Downloading mime v0.2.2
 Downloading num_cpus v1.2.1
 Downloading traitobject v0.0.1
 Downloading language-tags v0.2.2
 Downloading hpack v0.2.0
 Downloading sequence_trie v0.0.13
 Downloading ansi_term v0.9.0
 Downloading term_size v0.2.1
 Downloading unicode-segmentation v0.1.3
 Downloading strsim v0.5.2
 Downloading bitflags v0.7.0
 Downloading unicode-width v0.1.4
 Downloading vec_map v0.6.0
   Compiling itertools v0.4.19
   Compiling language-tags v0.2.2
   Compiling itoa v0.1.1
   Compiling traitobject v0.0.1
   Compiling crossbeam v0.2.10
   Compiling ascii v0.7.1
   Compiling dtoa v0.2.2
   Compiling semver v0.1.20
   Compiling bitflags v0.7.0
   Compiling strsim v0.5.2
   Compiling num-traits v0.1.36
   Compiling unicode-segmentation v0.1.3
   Compiling matches v0.1.4
   Compiling winapi-build v0.1.1
   Compiling rustc_version v0.1.7
   Compiling unicode-width v0.1.4
   Compiling utf8-ranges v0.1.3
   Compiling combine v2.0.0
   Compiling modifier v0.1.0
   Compiling ansi_term v0.8.0
   Compiling unicase v1.4.0
   Compiling byteorder v0.4.2
   Compiling tempfile v2.1.4
   Compiling winapi v0.2.8
   Compiling sequence_trie v0.0.13
   Compiling getopts v0.2.14
   Compiling kernel32-sys v0.2.2
   Compiling ansi_term v0.9.0
   Compiling libc v0.2.19
   Compiling memchr v0.1.11
   Compiling num_cpus v0.2.13
   Compiling aho-corasick v0.5.3
   Compiling num_cpus v1.2.1
   Compiling rand v0.3.15
   Compiling httparse v1.2.1
   Compiling unicode-bidi v0.2.4
   Compiling gcc v0.3.41
   Compiling tempdir v0.3.5
   Compiling chan v0.1.18
   Compiling typeable v0.1.2
   Compiling unicode-normalization v0.1.3
   Compiling idna v0.1.0
   Compiling rustc-serialize v0.3.22
   Compiling url v1.2.4
   Compiling tantivy v0.2.0
Build failed, waiting for other jobs to finish...
error: failed to compile `tantivy-cli v0.2.0`, intermediate artifacts can be found at `C:\Users\chvl\AppData\Local\Temp\cargo-install.ZLPYRvojBNiN`

Caused by:
  failed to run custom build command for `tantivy v0.2.0`
process didn't exit successfully: `C:\Users\chvl\AppData\Local\Temp\cargo-install.ZLPYRvojBNiN\release\build\tantivy-1d50d580f327910c\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to make simdcomp: Не удается найти указанный файл. (os error 2)', C:\Users\chvl\.cargo\registry\src\github.com-1ecc6299db9ec823\tantivy-0.2.0\build.rs:11
note: Run with `RUST_BACKTRACE=1` for a backtrace.

> **Failed to make simdcomp: Не удается найти указанный файл** (Can not find the file specified)

**Comment by vchugreev** [comment]
D:\Projects>cargo -V
cargo 0.17.0-nightly (40a4ce6 2017-01-06)

D:\Projects>rustc --version
rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)

**Comment by fulmicoton** [comment]
Yes you are right. tantivy-cli was always compiling with simd compression.

If you checkout "develop" you should be able to compile now with 

    cargo build --no-default-features


I think at one point, maybe you might want to consider setting up GCC or msvc properly if you want
to get better performance out of tantivy.

**Comment by vchugreev** [comment]
Ok. I just do not know how to do it, I will study. For its part, I encourage you to maximally facilitate the compilation process. Now a high threshold of entry into the project.

**Comment by fulmicoton** [comment]
No you misunderstand me, I committed a fix yesterday so that "--no-default-features" also has an effect on tantivy-cli. Please checkout the last version of develop and try to compile it.

I understand your frustration, but it works out of the box if you have a C++ compiler properly configured on your machine. This is quite usual for developers working on MacOS or Windows. I will consider making nosimdcompression the default though.

**Comment by vchugreev** [comment]
cargo build --no-default-features
Now it works

**Comment by fulmicoton** [comment]
Cool!

**Comment by vchugreev** [comment]
> I understand your frustration, but it works out of the box if you have a C++ compiler properly configured on your machine.

What is right?

D:\Projects\tantivy-cli>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-6.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 6.2.0 (Rev2, Built by MSYS2 project)

**Comment by vchugreev** [comment]
I have it already in use

**Comment by fulmicoton** [comment]
Can you send me the output of 

    cargo build -v

?

**Comment by vchugreev** [comment]
D:\Projects\tantivy-cli>cargo build
 Downloading version v2.0.1
   Compiling unicode-normalization v0.1.3
   Compiling semver v0.1.20
...
   Compiling tantivy v0.2.0

Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `tantivy v0.2.0`
process didn't exit successfully: `D:\Projects\tantivy-cli\target\debug\build\tantivy-050f0d27eb6a8e0a\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to make simdcomp: Не удается найти указанный файл. (os error 2)', C:\Users\chvl\.cargo\registry\src\github.com-1ecc6299db9ec823\tantivy-0.2.0\build.rs:11
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Не удается найти указанный файл = Can not find the file specified

**Comment by vchugreev** [comment]
D:\Projects\tantivy-cli>cargo -V
cargo 0.17.0-nightly (40a4ce6 2017-01-06)

**Comment by fulmicoton** [comment]
Also can you tell send me the result of  

    ls cpp/simdcomp/

**Comment by fulmicoton** [comment]
hmmm... Come to think about it, your problem is probably that you need `make`.

**Comment by vchugreev** [comment]
I have a Windows console :)
![1](https://cloud.githubusercontent.com/assets/10104106/21879067/5c328aba-d8a7-11e6-8320-2d086ae16253.png)

**Comment by vchugreev** [comment]
C:\Users\chvl\.cargo\registry\src\github.com-1ecc6299db9ec823\tantivy-0.2.0\cpp>dir /s>filelist.txt
[filelist.txt](https://github.com/tantivy-search/tantivy-cli/files/700823/filelist.txt)

**Comment by vchugreev** [comment]
In the file is a small problem with the encoding, but this is not essential.

**Comment by fulmicoton** [comment]
Can you run 

    nmake -f makefile.vc

from the cpp/simdcomp directory and tell me if `.o` appear? Sorry I don't have access to a windows machine.

**Comment by vchugreev** [comment]
nmake 
?

**Comment by vchugreev** [comment]
"Nmake" is not an internal or external command, operable program or batch file.

**Comment by fulmicoton** [comment]
Well, I am afraid `simdcomp` will be considered unsupported on windows from now on.

**Comment by vchugreev** [comment]
In general, my need to deal with the compilation of this library on Windows. Correctly?

**Comment by fulmicoton** [comment]
I don't understand your sentence.

**Comment by vchugreev** [comment]
Okay, it does not matter.

**Comment by vchugreev** [comment]
In any case, thank you.
